# Generated by Django 5.2.17 on 2026-08-06 15:24

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("subject", models.CharField(max_length=100)),
                ("exam_date", models.DateField()),
                ("total_marks", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exams",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("number", models.CharField(max_length=10)),
                ("text", models.TextField()),
                ("max_marks", models.DecimalField(decimal_places=2, max_digits=5)),
                ("model_answer", models.TextField()),
                ("model_answer_hash", models.CharField(blank=True, default="", max_length=64)),
                ("concepts_indexed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="exams.exam",
                    ),
                ),
            ],
            options={
                "ordering": ["number"],
            },
        ),
        migrations.CreateModel(
            name="Concept",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("text", models.TextField()),
                ("weight", models.FloatField()),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("embedding", pgvector.django.vector.VectorField(dimensions=1024)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="concepts",
                        to="exams.question",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "indexes": [
                    pgvector.django.indexes.IvfflatIndex(
                        fields=["embedding"],
                        lists=100,
                        name="concept_embedding_ivfflat",
                        opclasses=["vector_cosine_ops"],
                    )
                ],
            },
        ),
    ]
