# Generated by Django 5.2.17 on 2026-08-26 07:22

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0002_delete_stale_concepts"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="concept",
            name="concept_embedding_ivfflat",
        ),
        migrations.AlterField(
            model_name="concept",
            name="embedding",
            field=pgvector.django.vector.VectorField(dimensions=2048),
        ),
    ]
