# Generated by Django 5.2.17 on 2026-09-24 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_remove_concept_concept_embedding_ivfflat_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('exam', 'number'), name='unique_question_number_per_exam'),
        ),
    ]
